language: node_js
node_js:
  - 'lts/*'
install:
  - pnpm install
  - pnpm install -g surge
script:
  - pnpm run build:doc
  - surge ./dist ahooks-$(git rev-parse --short HEAD).surge.sh
cache:
  directories:
    - 'node_modules'
